python BATCH_RETR.py --loc_name ARIZONA_MINE
python BATCH_RETR.py --loc_name SLC_MINE
python BATCH_RETR.py --loc_name RIYADH_PLANT_9
python BATCH_RETR.py --loc_name XAI_CENTER
python BATCH_RETR.py --loc_name Limestone
python BATCH_RETR.py --loc_name Fort_Martin_Power_Station
python BATCH_RETR.py --loc_name Ninemile_Point
python BATCH_RETR.py --loc_name Scherer
python BATCH_RETR.py --loc_name Ghent
python BATCH_RETR.py --loc_name Miami_Fort_Power_Station
python BATCH_RETR.py --loc_name Hunter
python BATCH_RETR.py --loc_name Labadie
python BATCH_RETR.py --loc_name W_A_Parish
python BATCH_RETR.py --loc_name Thomas_Hill_Energy_Center
python BATCH_RETR.py --loc_name Belle_River
python BATCH_RETR.py --loc_name Milton_R_Young
python BATCH_RETR.py --loc_name Cayuga
